### ISSUE TITLE
Single header missing code in v0.8.3

### ISSUE THREAD

**Issue by nxrighthere** [richardbiely/gaia-ecs#19]
The implementation of `void join_thread(uint32_t workerIdx)` missing code for `auto& t = m_workers[i];`. `i` is undeclared.

**Comment by nxrighthere** [comment]
I guess `workerIdx` is the actual parameter.

**Comment by richardbiely** [comment]
Thank you! I failed to notice I did not push the fix from my Windows machine before the release.

Fixed in 0.8.4.
